# Generated by Django 5.1.2 on 2024-11-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_achievements_user_applicant_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='csa_typing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='user_typing',
            field=models.BooleanField(default=False),
        ),
    ]
