# Generated by Django 5.1.1 on 2024-10-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_todolist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='uploadedimage',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
