# Generated by Django 5.1.2 on 2024-11-25 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_chatrequest_csa_typing_chatrequest_user_typing'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryCapturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_captured', models.ImageField(blank=True, null=True, upload_to='captured_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captured_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
