# Generated by Django 5.1.2 on 2024-11-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_deviceinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceInfo',
        ),
    ]
