# Generated by Django 5.1.2 on 2024-11-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
