# Generated by Django 5.1.2 on 2024-11-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='ChatRequestId',
        ),
        migrations.RemoveField(
            model_name='video',
            name='recorderd_user_id',
        ),
        migrations.AddField(
            model_name='video',
            name='chat_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='recorded_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(default='waiting', max_length=50),
        ),
    ]
