# Generated by Django 5.1.2 on 2024-11-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_video_chatrequestid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
