# Generated by Django 5.1.2 on 2024-11-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_user_logout_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCount_csa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('csa_id', models.IntegerField(blank=True, null=True)),
                ('message_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageCount_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('csa_id', models.IntegerField(blank=True, null=True)),
                ('message_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
